### ISSUE TITLE
wrong cd command in makefile

### ISSUE THREAD

**Issue by AkashS20** [meshery/play#103]
#### Current Behavior

The `cd..` command in makefile, [here](https://github.com/meshery/play/blob/master/Makefile#L36) is wrong.
#### Expected Behavior

It should be `cd ..`

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by thisiskaransgit** [comment]
Though it is not a "wrong" command, since there's no behavioral change in the outcome, it's better to follow the code conventions, you can go ahead and provide a quick fix.

Additionally, 
1. Update the "Layer Community Welcome Guide" link to [Newcomers' Guide](https://layer5.io/community/newcomers/) in Readme.md
2. Update the play website preview image, (the toggle button was in the center earlier, the website is updated now) in Readme.md

incorporate these changes in a single PR and mention the changes made
