### ISSUE TITLE
Inappropriate Display of Signup Button for Users with Cookies

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/play#177]
#### Current Behavior

The website currently displays a signup button regardless of whether the user has an account indicating prior signup. This behavior is not consistent with user expectations and may lead to confusion.

Possible Solution:

Implement logic to check for the presence of a signup-related cookie. If the cookie is present, do not display the signup button. Ensure this check is performed consistently across page loads.

#### Screenshots/Logs

![image](https://github.com/meshery/play/assets/59491379/b01db33a-0d79-45ad-8e4e-5686bd215e24)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by prajjwalyd** [comment]
Hello!

I've been exploring the signup button behavior issue, and I'd like to propose a solution:

**Step 1:**
Utilize the `useEffect` hook to check for the presence of the signup-related cookie on component mount.

**Step 2:**
Initialize the `showSignUpButton` state based on the presence of the cookie.

**Step 3:**
When the user submits the signup form, set the signup-related cookie, and update the `showSignUpButton` state accordingly.

---

If this solution aligns with your expectations, I'd be excited to take ownership of this issue and work on implementing it. Please let me know if any adjustments are needed or if you have any specific considerations...

**Comment by prajjwalyd** [comment]
Hello!

I've been exploring the signup button behavior issue, and I'd like to propose a solution:

**Step 1:**
Check for the presence of the signup-related cookie on mount.

**Step 2:**
Initialize the `showSignUpButton` state based on the presence of the cookie.

**Step 3:**
When the user submits the signup form, set the signup-related cookie, and update the `showSignUpButton` state accordingly.

---
If this solution aligns with your expectations, I'd be excited to take ownership of this issue and work on implementing it. Please let me know if any adjustments are needed or if you have any specific considerations...

**Comment by prajjwalyd** [comment]
Hey @captain-Akshay , 
any updates on this issue?

**Comment by Shabab007** [comment]
Hello @captain-Akshay @leecalcote 
I have looked into the issue . achieving the desired functionality of checking the presence of the signup-related cookie for not displaying the signup button involves a series of critical steps.  . here are some findings

1. After signing up the api response header is setting the http only cookie named  "__cf_bm" which is expected.
here is the screenshot

<img width="1084" alt="Screenshot 2024-02-08 at 7 09 37 PM" src="https://github.com/meshery/play/assets/90137571/ae8bb002-e969-48a3-9fc9-3ea6b2ec3b49">

2. As this app is built  with Create react app which is client side app, Javascript can not get or access http only cookies thats why we cant determine whether the user has cookie or not. 

Suggestions might help
- In order to achieve and parse the cookie we need to use Next js or serverside technology .
- We can use hybrid auth system like jwt with cookie in order get the user creds, permissions, authorization and the http only cookie will be set for the subsequent api request for that user

**Comment by leecalcote** [comment]
> Hey @captain-Akshay , any updates on this issue? Is it still valid?

Yes, indeed, it certainly is.

**Comment by leecalcote** [comment]
The need here isn't with respect as to whether someone has signed up, but whether they have been awarded access to the Playground or not. The cookie for this will come from meshery.meshery.io. While you're digging in here, @Shabab007, please note the sibling issue here - https://github.com/meshery/meshery/issues/5295. We'll want for these to both be handled in the same way. Both sites use Gatsby and both will need to look for the same cookie/access/token.

**Comment by Shabab007** [comment]
Hi @leecalcote ,
After carefully looking at the issue and sibling issue . I found that playground is in different domain play.meshery.io and the cookie we are expecting that should come from meshery.meshery.io domain. Indeed, cookies are typically restricted to the domain from which they were set due to the same-origin policy, a security measure implemented by web browsers. Thats why we can't access the cookies from different domain to toggle off the playground button.

**Comment by leecalcote** [comment]
Maybe, maybe not.

**Comment by leecalcote** [comment]
My money is on the latter.

**Comment by prajjwalyd** [comment]
@leecalcote From what I've understood, the goal here is to show the signup button based on the presence of a cookie that will come from meshery.meshery.io, but we want to access that from https://play.meshery.io/... in this situation, I think @Shabab007's concern is spot on as we can't access cookies between domains without any Centralized Authentication or cross-domain messaging kind of things.
Please correct me if I've misunderstood anything.
